name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install .[tests]

    - name: Run ruff
      working-directory: recipe_recommendation
      run: |
        ruff check .
        ruff format --diff .

    - name: Type checking with mypy
      working-directory: recipe_recommendation
      run: mypy . --install-types --non-interactive

    - name: Run tests
      run: pytest
