name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements-test.txt

    - name: Install package
      run: pip install -e . --no-deps

    - name: Run ruff
      run: |
        ruff check ./recipe_recommendation
        ruff format --diff ./recipe_recommendation

    - name: Type checking with mypy
      run: mypy ./recipe_recommendation --install-types --non-interactive

    - name: Run tests
      run: pytest ./tests
